# Generated by Django 3.1.3 on 2020-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Done'), (3, 'Postponed'), (4, 'Ignored')], default=1),
        ),
    ]
