# Generated by Django 3.1.3 on 2020-11-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
    ]
