# Generated by Django 3.1.3 on 2020-11-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201121_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'time', '-priority']},
        ),
    ]
