# Generated by Django 3.1.3 on 2020-11-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.goal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.IntegerField(choices=[(1, 'Yearly'), (2, 'Monthly'), (3, 'Weekly')]),
        ),
    ]
