# Generated by Django 3.1.3 on 2020-11-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20201123_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate_time',
            field=models.IntegerField(default=0),
        ),
    ]
