# Generated by Django 3.1.3 on 2020-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20201124_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermGoal',
            fields=[
            ],
            options={
                'verbose_name': 'Long-Term Goal',
                'verbose_name_plural': 'Long-Term Goals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.goal',),
        ),
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.goal',),
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.goal',),
        ),
        migrations.CreateModel(
            name='YearlyGoal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.goal',),
        ),
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.IntegerField(choices=[(1, 'Long Term'), (2, 'Yearly'), (3, 'Monthly'), (4, 'Weekly')]),
        ),
    ]
