# Generated by Django 3.1.3 on 2020-11-28 19:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_thisweektask'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextWeekTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
