# Generated by Django 3.1.3 on 2020-12-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20201211_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.IntegerField(choices=[(1, 'Long Term'), (2, 'Yearly'), (3, 'Monthly'), (4, 'Weekly')], default=1),
        ),
    ]
