# Generated by Django 3.1.3 on 2020-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20201211_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimate_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
